### ISSUE TITLE
Possible build/push glitch

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-4.70#45]
There maybe a possible build glitch in `572` where it'll duplicate binaries, therefore inflating the repo from ~450 MB to 2.53 GB.

**Comment by Smurf-IV** [comment]
Is this because of the `Failsafe/Krypton Components` area ?

Or when a new Sync is done it is not removing the Old Built binaries which were scattered all over the place ?

**Comment by Wagnerp** [comment]
It seems that all binaries `*.dll` and `*.exe` etc are built in each of the main directories as well as the top level directory, unless this is a problem in the `4.71` version only?

**Comment by Smurf-IV** [comment]
That is correct for the build locations, The binaries are then copied if they are different as a post build.
This allows the compiler to find the relevant files quicker when performing debug actions as they remain specific to the build project rather than being replaced by other projects.
Those files shoulde not be pushed to Github as they are excluded by the gitignore file.
